// Blog Functionality
document.addEventListener('DOMContentLoaded', function() {
    // Check if we're on the blog page
    const blogPostsContainer = document.getElementById('blog-posts-container');
    
    if (blogPostsContainer) {
        // Fetch blog posts from the blog directory
        fetchBlogPosts();
    }
    
    // Check if we're on a single blog post page
    const blogPostContent = document.querySelector('.blog-post-content');
    
    if (blogPostContent) {
        // Get the post ID from the URL
        const urlParams = new URLSearchParams(window.location.search);
        const postId = urlParams.get('id');
        
        if (postId) {
            fetchSingleBlogPost(postId);
        }
    }
    
    // Function to fetch all blog posts
    function fetchBlogPosts() {
        // In a real implementation, this would fetch from your CMS
        // For now, we'll use a fetch request to a JSON file that will be generated by the CMS
        fetch('/blog/index.json')
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            })
            .then(posts => {
                displayBlogPosts(posts);
            })
            .catch(error => {
                console.error('Error fetching blog posts:', error);
                displayErrorMessage(blogPostsContainer);
            });
    }
    
    // Function to fetch a single blog post
    function fetchSingleBlogPost(postId) {
        // In a real implementation, this would fetch from your CMS
        fetch(`/blog/${postId}.json`)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            })
            .then(post => {
                displaySingleBlogPost(post);
            })
            .catch(error => {
                console.error('Error fetching blog post:', error);
                displayErrorMessage(blogPostContent.parentElement);
            });
    }
    
    // Function to display blog posts
    function displayBlogPosts(posts) {
        // Clear loading spinner
        blogPostsContainer.innerHTML = '';
        
        // Check if there are any posts
        if (posts.length === 0) {
            blogPostsContainer.innerHTML = '<div class="no-posts">No blog posts found.</div>';
            return;
        }
        
        // Sort posts by date (newest first)
        posts.sort((a, b) => new Date(b.date) - new Date(a.date));
        
        // Create blog cards for each post
        posts.forEach(post => {
            const blogCard = createBlogCard(post);
            blogPostsContainer.appendChild(blogCard);
        });
    }
    
    // Function to create a blog card
    function createBlogCard(post) {
        const card = document.createElement('div');
        card.className = 'blog-card';
        
        // Format date
        const postDate = new Date(post.date);
        const formattedDate = postDate.toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });
        
        // Create excerpt from content (first 150 characters)
        const excerpt = post.description || post.content.substring(0, 150) + '...';
        
        // Create HTML for the card
        card.innerHTML = `
            ${post.thumbnail ? `<img src="${post.thumbnail}" alt="${post.title}" class="blog-card-image">` : ''}
            <div class="blog-card-content">
                <div class="blog-card-date">${formattedDate}</div>
                <h2 class="blog-card-title">${post.title}</h2>
                <p class="blog-card-excerpt">${excerpt}</p>
                <a href="blog-post.html?id=${post.id}" class="blog-card-link">Read More</a>
                ${post.tags && post.tags.length > 0 ? `
                    <div class="blog-card-tags">
                        ${post.tags.map(tag => `<span class="blog-card-tag">${tag}</span>`).join('')}
                    </div>
                ` : ''}
            </div>
        `;
        
        return card;
    }
    
    // Function to display a single blog post
    function displaySingleBlogPost(post) {
        // Get elements
        const titleElement = document.querySelector('.blog-post-title');
        const dateElement = document.querySelector('.blog-post-date');
        const imageElement = document.querySelector('.blog-post-image');
        const contentElement = document.querySelector('.blog-post-content');
        const tagsContainer = document.querySelector('.blog-post-tags');
        
        // Format date
        const postDate = new Date(post.date);
        const formattedDate = postDate.toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });
        
        // Update elements
        document.title = `${post.title} | AsphaltCalculator.co`;
        titleElement.textContent = post.title;
        dateElement.textContent = formattedDate;
        
        if (post.thumbnail && imageElement) {
            imageElement.src = post.thumbnail;
            imageElement.alt = post.title;
        } else if (imageElement) {
            imageElement.style.display = 'none';
        }
        
        // Set content (this would be HTML from the CMS)
        contentElement.innerHTML = post.content;
        
        // Add tags if they exist
        if (post.tags && post.tags.length > 0 && tagsContainer) {
            tagsContainer.innerHTML = post.tags.map(tag => `<span class="blog-post-tag">${tag}</span>`).join('');
        } else if (tagsContainer) {
            tagsContainer.style.display = 'none';
        }
    }
    
    // Function to display an error message
    function displayErrorMessage(container) {
        container.innerHTML = `
            <div class="error-message">
                <i class="fas fa-exclamation-circle"></i>
                <p>Sorry, we couldn't load the blog posts at this time. Please try again later.</p>
            </div>
        `;
    }
});
