// Pages Functionality
document.addEventListener('DOMContentLoaded', function() {
    // Check if we're on a page with dynamic content
    const pageContentContainer = document.getElementById('page-content');
    
    if (pageContentContainer) {
        // Get the current page name from the URL or active nav item
        const currentPage = getCurrentPage();
        
        if (currentPage) {
            fetchPageContent(currentPage);
        }
    }
    
    // Function to get the current page name
    function getCurrentPage() {
        // Get the current page from the URL
        const path = window.location.pathname;
        const pageName = path.split('/').pop().replace('.html', '');
        
        // If we're on the index page, return null
        if (pageName === 'index' || pageName === '') {
            return null;
        }
        
        return pageName;
    }
    
    // Function to fetch page content
    function fetchPageContent(pageName) {
        // In a real implementation, this would fetch from your CMS
        // For now, we'll use a fetch request to a JSON file that will be generated by the CMS
        fetch(`/pages/${pageName}.json`)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            })
            .then(pageData => {
                displayPageContent(pageData);
            })
            .catch(error => {
                console.error('Error fetching page content:', error);
                displayDefaultContent(pageName);
            });
    }
    
    // Function to display page content
    function displayPageContent(pageData) {
        // Clear loading spinner
        pageContentContainer.innerHTML = '';
        
        // Update page title and meta description
        if (pageData.title) {
            document.title = `${pageData.title} | AsphaltCalculator.co`;
        }
        
        if (pageData.description) {
            const metaDescription = document.querySelector('meta[name="description"]');
            if (metaDescription) {
                metaDescription.setAttribute('content', pageData.description);
            }
        }
        
        // Set content (this would be HTML from the CMS)
        pageContentContainer.innerHTML = pageData.content;
    }
    
    // Function to display default content if fetching fails
    function displayDefaultContent(pageName) {
        pageContentContainer.innerHTML = '';
        
        if (pageName === 'about') {
            pageContentContainer.innerHTML = `
                <h2>About AsphaltCalculator.co</h2>
                <p>Welcome to AsphaltCalculator.co, your trusted resource for accurate asphalt calculations. Our mission is to provide contractors, engineers, and DIY enthusiasts with precise estimations for their asphalt paving projects.</p>
                
                <h3>Our Story</h3>
                <p>AsphaltCalculator.co was founded in 2025 by a team of civil engineers and web developers who recognized the need for a simple, accurate, and accessible tool for calculating asphalt requirements. After years of experience in the paving industry, we developed this calculator to help others save time and money on their projects.</p>
                
                <h3>Why Choose Our Calculator</h3>
                <ul>
                    <li><strong>Accuracy:</strong> Our calculator uses industry-standard formulas and conversion factors to provide highly accurate estimates.</li>
                    <li><strong>Ease of Use:</strong> The intuitive interface makes it simple for anyone to calculate their asphalt needs, regardless of technical expertise.</li>
                    <li><strong>Comprehensive Results:</strong> Get volume, weight, cost estimates, and even suggested mix types all in one place.</li>
                    <li><strong>Free to Use:</strong> We believe in providing value to the community, which is why our calculator is completely free to use.</li>
                </ul>
                
                <h3>Our Commitment</h3>
                <p>We are committed to continuously improving our calculator and providing educational resources through our blog to help you make informed decisions about your asphalt paving projects.</p>
                
                <p>Thank you for choosing AsphaltCalculator.co for your asphalt estimation needs. If you have any questions or feedback, please don't hesitate to <a href="contact.html">contact us</a>.</p>
            `;
        } else if (pageName === 'contact') {
            pageContentContainer.innerHTML = `
                <h2>Get in Touch</h2>
                <p>We'd love to hear from you! Whether you have questions about our calculator, suggestions for improvement, or just want to say hello, feel free to reach out to us using the contact form or email address below.</p>
                
                <p>Our team is dedicated to providing the best possible experience for our users, and your feedback helps us achieve that goal.</p>
            `;
        } else {
            pageContentContainer.innerHTML = `
                <h2>${pageName.charAt(0).toUpperCase() + pageName.slice(1)}</h2>
                <p>This page is currently under construction. Please check back soon for updates.</p>
            `;
        }
    }
});
