backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Publish mode option:
# - editorial_workflow (Documents have to be reviewed before they're published)
# - simple (Publish content directly after saving)
publish_mode: editorial_workflow

# Media folder where uploaded images will be stored in your repo
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  # Blog posts collection
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "SEO Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
  
  # Pages collection for About, Contact, etc.
  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Description", name: "description", widget: "text", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  
  # FAQ collection
  - name: "faq"
    label: "FAQ Items"
    folder: "faq"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Question", name: "question", widget: "string"}
      - {label: "Answer", name: "answer", widget: "markdown"}
      - {label: "Order", name: "order", widget: "number", default: 0}
